export default Questions = [
  {
    id: 1,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 2,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 3,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 4,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 5,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 6,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 7,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 8,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 9,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 10,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 11,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 12,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
  {
    id: 13,
    title: "რაღაც თაითლი",
    answers: {
      a: "პასუხი ა",
      b: "პასუხი ბ",
      c: "პასუხი გ",
      d: "პასუხი დ",
    },
    correctAnswer: "a",
  },
];
